// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLXGn2Y6GSi5W3Rh21RUm14zZczl1-EmY',
    appId: '1:728337102390:web:dc7234de9a8592bed04a97',
    messagingSenderId: '728337102390',
    projectId: 'flutter-project-e8dac',
    authDomain: 'flutter-project-e8dac.firebaseapp.com',
    storageBucket: 'flutter-project-e8dac.firebasestorage.app',
    measurementId: 'G-4Q9D9G04L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvdrlBlPmFW_s8QEOroa4R0K7zKEowS9c',
    appId: '1:728337102390:android:ba30631cb05c582ed04a97',
    messagingSenderId: '728337102390',
    projectId: 'flutter-project-e8dac',
    storageBucket: 'flutter-project-e8dac.firebasestorage.app',
  );
}
